# Generated by Django 3.1.2 on 2021-02-20 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_contact_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerpage',
            name='roll',
            field=models.CharField(default=1234, max_length=10),
            preserve_default=False,
        ),
    ]
