# Generated by Django 3.1.2 on 2021-02-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_answerpage_roll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerpage',
            name='email',
        ),
        migrations.AddField(
            model_name='contact',
            name='branch',
            field=models.CharField(default=1234, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='roll',
            field=models.CharField(default=1234, max_length=10),
            preserve_default=False,
        ),
    ]
