# Generated by Django 3.1.2 on 2021-02-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210223_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='regi',
            field=models.CharField(default=1234, max_length=10),
            preserve_default=False,
        ),
    ]
