# Generated by Django 3.1.2 on 2021-02-23 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_contact_regi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='regi',
            new_name='registration',
        ),
    ]
