# Generated by Django 3.1.2 on 2021-02-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210223_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='registration',
            field=models.CharField(max_length=100),
        ),
    ]
